//
// Created by Janney on 2024/3/5.
//

#ifndef OHOS_MULTIMEDIA_PLAYER_FRAMEWORK_OBSERVER_FUNC_UNITTEST_H
#define OHOS_MULTIMEDIA_PLAYER_FRAMEWORK_OBSERVER_FUNC_UNITTEST_H


class observer_func_unittest {

};


#endif //OHOS_MULTIMEDIA_PLAYER_FRAMEWORK_OBSERVER_FUNC_UNITTEST_H
